export const tags = {
  Origin: [
    "China",
    "India",
    "Belgium",
    "Sweden",
    "Germany",
    "Malaysia",
    "Turkey",
    "Italy",
    "New Zealand",
    "Vietnam",
    "Worldwide",
    "Australia",
    "Thailand",
    "Netherland",
    "Japan",
    "Indonesia",
    "Philippines",
    "Europe",
    "Southeast Asia",
    "Singapore",
    "Spain",
  ],
  Destination: [
    "Usa",
    "Vietnam",
    "Canada",
    "Belgium",
    "Philippines",
    "Malaysia",
    "Australia",
    "Brazil",
    "Trinidad & Tobago",
    "Japan",
    "Qatar",
    "Germany",
    "Laos",
    "Myanmar",
    "Cambodia",
    "Uae",
    "Middle East",
    "South Africa",
    "Angola",
    "Singapore",
    "Indonesia",
  ],
  Commodity: [
    "Surge Bin",
    "Structural Steel",
    "Renewable Energy System",
    "Patrol Boats",
    "Amazon River Cruise Boat",
    "Liftboat",
    "Drydock",
    "Mobile",
    "Shiploader",
    "Steel Structures",
    "Transformer And Accessories",
    "Steel Pipe Column",
    "Floating Pontoons",
    "Steel Beams",
    "Heavy Equipment",
    "Equipment For Pipelines",
    "Dump Trays",
    "General Cargo",
    "Machinery And Equipment",
    "Man Engine",
    "Lifeboats",
    "Gas Turbine Generator",
    "Compressor Modules & E-Houses",
    "Saudi Arabia",
    "Pipe-Racks, Skids, Spools",
    "Substation Module",
    "Waste Heat Recovery Units",
    "Blades And Tower",
    "Vacuum Insulated Pipe Spools",
    "Substation",
    "Modules",
    "Raw Materials",
    "Components For Steel Mills",
  ],
  "Bussiness Unit": ["Project", "Logistic", "Warehousing", "Trading"],
};

// 100 random post titles
export const randomPostTitle = [
  "Local Business Owner Wins Lottery",
  "City Council Approves New Budget",
  "Severe Storms Cause Widespread Damage",
  "Traffic Delays Expected Due to Construction",
  "Missing Child Found Safe",
  "Celebrity Spotted in Local Restaurant",
  "Firefighters Battle Blaze at Abandoned Building",
  "New School Opens Doors to Students",
  "Police Investigate Suspicious Package",
  "Local Artist Wins Prestigious Award",
  "Community Rallies to Support Homeless Shelter",
  "Dog Rescued from River",
  "Power Outage Affects Thousands of Homes",
  "Debate Heats Up Over Proposed Development",
  "Local Team Wins Championship",
  "Winter Storm Warning Issued",
  "Scientists Discover New Species",
  "Job Fair Draws Large Crowd",
  "Police Seek Information on Hit-and-Run",
  "Local Farmer Wins Award for Best Produce",
  "Stocks Plunge on Recession Fears",
  "Heat Wave Grips Southern States",
  "Scientists Discover New Planet",
  "Cyberattack Disrupts Major Companies",
  "Supreme Court Rules on Key Issue",
  "Wildfires Rage in Western Forests",
  "Hurricane Threatens Coastal Communities",
  "Tech Giant Announces New Product",
  "Poll Shows Tight Race for Governor",
  "Artist Breaks World Record",
  "Massive Earthquake Strikes Pacific Rim",
  "Nobel Prize Awarded to Scientist",
  "Government Investigates Corruption Scandal",
  "Winter Storm Paralyzes Transportation",
  "SpaceX Launches Another Mission",
  "Music Legend Dies at 75",
  "Rare Disease Outbreak Reported",
  "Landmark Climate Agreement Reached",
  "Social Media Giant Faces Antitrust Lawsuit",
  "Record-Breaking Heat Wave Scorches Europe",
  "Study Links Diet to Disease",
  "New Drug Shows Promise in Trials",
  "Experts Warn of AI Dangers",
  "Climate Change Fuels Extreme Weather",
  "Tech Companies Face Scrutiny",
  "Immigration Debate Heats Up",
  "Farmers Struggle with Drought",
  "Tourism Boom Strains Resources",
  "Artists Protest Copyright Laws",
  "Teachers Demand Higher Salaries",
  "Energy Crisis Looms as Winter Nears",
  "Social Media Addiction on the Rise",
  "Ancient Ruins Unearthed in Excavation",
  "Food Shortages Threaten Global Markets",
  "Space Tourism Takes Off",
  "Cybersecurity Breaches on the Rise",
  "Affordable Housing Crisis Worsens",
  "Students Protest Tuition Increases",
  "Policing Reforms Under Scrutiny",
  "Aging Population Strains Healthcare System",
  "Record-Breaking High Temperatures",
  "Vaccine Mandates Face Legal Challenges",
  "Cryptocurrency Market Crashes",
  "Artificial Intelligence Revolutionizes Healthcare",
  "Global Supply Chain Disruptions",
  "Extreme Weather Events Increase",
  "Water Shortages Threaten Communities",
  "New York City Faces Housing Crisis",
  "Amazon Expands Grocery Delivery",
  "Scientists Warn of Mass Extinction",
  "Election Day Sees Record Turnout",
  "Social Media Fuels Misinformation",
  "Autonomous Vehicles Hit the Roads",
  "Artists Boycott Streaming Platforms",
  "Refugee Crisis Deepens in Europe",
  "Farmers Protest Low Crop Prices",
  "Nuclear Power Plant Faces Safety Concerns",
  "Space Race Heats Up Between Nations",
  "Scientists Discover New Antibiotic",
  "Cyberattacks Target Critical Infrastructure",
  "E-commerce Booms During Pandemic",
  "Rise of Remote Work Changes Lifestyles",
  "Aging Infrastructure Needs Urgent Repairs",
  "Mental Health Crisis Among Young People",
  "Sports Leagues Grapple with Concussions",
  "Fast Fashion Industry Under Fire",
  "Rise of Populism Across the Globe",
  "Celebrity Scandals Dominate Headlines",
  "Tourism Industry Struggles to Recover",
  "Rise of the Gig Economy",
  "Climate Change Impacts Food Security",
  "Data Breaches Expose User Privacy",
  "Artificial Intelligence Bias Concerns",
  "Rise of Veganism and Vegetarianism",
  "Urban Farming Gains Popularity",
  "Decline of Traditional Media",
  "Rise of E-sports and Gaming Culture",
  "Space Tourism Becomes More Accessible",
  "Renewable Energy Sources Gain Traction",
  "Rise of the Sharing Economy",
];

// 100 random post content
export const randomPostContent = [
  'John Smith, owner of "Smith\'s Diner," claimed a $1 million lottery prize. He plans to use the winnings to expand his business and donate to local charities.',
  "The city council voted unanimously to approve the 2024 budget, which includes funding for road repairs, a new community center, and increased police presence.",
  "Strong winds and heavy rain battered the region, causing downed trees, power outages, and flooding in several neighborhoods. Emergency crews are working to restore services.",
  "Motorists should expect significant traffic delays on Main Street due to ongoing road construction. Detours are in place, and drivers are advised to allow extra travel time.",
  "A five-year-old child reported missing earlier today has been found safe and returned to their family. Police are thanking the community for their assistance in the search.",
  'Hollywood actor, Tom Cruise, was spotted dining at "The Cozy Cafe" this afternoon. He reportedly enjoyed a quiet meal with friends before continuing his travels.',
  "A fire broke out this morning at an abandoned warehouse downtown. Firefighters responded quickly and brought the blaze under control, but the building suffered significant damage.",
  'The highly anticipated "Sunshine Elementary" opened its doors to students today. The new school features state-of-the-art classrooms, a modern library, and a spacious playground.',
  "Police are investigating a suspicious package found at the city hall this morning. The building was evacuated as a precaution, and the bomb squad is currently examining the package.",
  'Emily Jones, a renowned local painter, has been awarded the prestigious "Golden Brush Award" for her exceptional contributions to the art community.',
  'Local businesses and residents are coming together to support the "Hope Shelter" with donations of food, clothing, and blankets as the winter season approaches.',
  "A heroic passerby jumped into the river to rescue a dog that had fallen through the ice. Both the dog and the rescuer were unharmed and reunited with the dog's owner.",
  "A sudden power outage is affecting thousands of homes across the city. Utility crews are working to restore power as quickly as possible, but the estimated restoration time is unknown.",
  "A heated debate has erupted among residents over a proposed development project that would replace a local park with a high-rise apartment complex.",
  'The "City Thunder" baseball team clinched the championship title last night with a thrilling victory over their rivals. The team was met with cheers and celebrations from the enthusiastic crowd.',
  "A winter storm warning has been issued for the region, with heavy snowfall and icy conditions expected. Residents are advised to stay indoors if possible and prepare for travel delays.",
  "A team of local scientists has made a groundbreaking discovery, identifying a previously unknown species of butterfly in the nearby nature reserve.",
  "Hundreds of job seekers attended the city's annual job fair today, connecting with potential employers from various industries.",
  "Police are seeking information from the public regarding a hit-and-run accident that occurred last night. Witnesses are urged to come forward with any information they may have.",
  'Johnathan Miller, a local organic farmer, has been awarded the "Golden Zucchini" for producing the best quality zucchini at the annual county fair.',
  "A magnitude 7.2 earthquake struck the coast of Chile, causing significant damage to infrastructure and triggering a tsunami warning. Emergency crews are working to assess the damage and assist those affected.",
  "The United Nations issued a stark warning about the accelerating pace of climate change, urging immediate and drastic action to reduce greenhouse gas emissions and mitigate the worst impacts.",
  "A new study published in the journal Nature found a strong link between air pollution and cognitive decline in older adults, highlighting the urgent need to improve air quality.",
  "A major cyberattack crippled several critical infrastructure systems in a European country, disrupting transportation, energy, and financial services. Authorities are investigating the source of the attack.",
  "The International Space Station successfully conducted a spacewalk to repair a vital piece of equipment, averting a potential crisis for the orbiting laboratory.",
  "A groundbreaking new cancer treatment has shown promising results in early clinical trials, offering hope for patients with previously untreatable forms of the disease.",
  "A severe drought is impacting agricultural production across several regions, leading to concerns about food shortages and rising prices.",
  "A major political scandal erupted after leaked documents revealed evidence of corruption within the highest levels of government.",
  "A historic agreement was reached between two long-time adversaries, ending decades of conflict and paving the way for peace and reconciliation.",
  "A wildfire raging in the western United States has forced thousands of residents to evacuate their homes, as firefighters struggle to contain the blaze.",
  "A new report from the World Health Organization warns of a global resurgence of infectious diseases, urging increased investment in public health infrastructure.",
  "A landmark Supreme Court ruling overturned a controversial law, sparking widespread protests and calls for further legal action.",
  "A major oil spill off the coast of California has caused significant environmental damage, threatening marine life and coastal ecosystems.",
  "A powerful hurricane is expected to make landfall in the coming days, prompting mandatory evacuations and emergency preparations.",
  "A groundbreaking new technology has the potential to revolutionize renewable energy production, offering a cleaner and more sustainable future.",
  "A major earthquake struck a densely populated region, causing widespread destruction and leaving thousands homeless.",
  "A new study found that a common household chemical may be linked to an increased risk of certain types of cancer, prompting calls for stricter regulations.",
  "A historic summit between world leaders concluded with a commitment to address global challenges such as climate change, poverty, and inequality.",
  "A major tech company announced a new product that is expected to revolutionize the way people interact with technology.",
  "A severe winter storm has paralyzed transportation across much of the country, leaving millions stranded and facing power outages.",
  "A team of scientists has made a groundbreaking discovery, identifying a new species of dinosaur in a remote region of South America.",
  "A major art heist has left authorities baffled, with priceless works of art stolen from a world-renowned museum.",
  "A new report warns of a looming global food crisis, driven by climate change, conflict, and economic instability.",
  "A major social media platform has been accused of spreading misinformation and inciting violence, facing calls for increased regulation.",
  "A groundbreaking new medical procedure has successfully restored sight to a patient who had been blind for years.",
  "A major volcanic eruption has forced the evacuation of thousands of residents, as lava flows threaten to engulf nearby villages.",
  "A new study found that a widely used medication may have serious side effects, prompting a recall and raising concerns about patient safety.",
  "A historic election has resulted in a major shift in the political landscape, with a new leader promising to usher in an era of change.",
  "A major flood has inundated entire communities, leaving thousands of people displaced and in need of emergency assistance.",
  "A team of scientists has successfully landed a spacecraft on a distant asteroid, marking a significant milestone in space exploration.",
  "A major wildfire has ravaged a popular tourist destination, destroying homes and businesses and forcing the evacuation of thousands of visitors.",
  "A new report warns of a global water crisis, as rising demand and declining supplies threaten to exacerbate conflicts and displacement.",
  "A major earthquake has struck a densely populated region, causing widespread destruction and leaving thousands homeless.",
  "A historic agreement has been reached between world leaders to reduce greenhouse gas emissions and combat climate change.",
  "A major tech company has announced plans to lay off thousands of employees, citing economic uncertainty and declining revenues.",
  "A new study has found that a common household chemical may be linked to an increased risk of certain types of cancer, prompting calls for stricter regulations.",
  "A major political scandal has erupted, with allegations of corruption and abuse of power by high-ranking officials.",
  "A powerful hurricane has made landfall, causing widespread devastation and leaving millions without power.",
  "A groundbreaking new medical procedure has successfully restored sight to a patient who had been blind for years.",
  "A major oil spill has caused significant environmental damage, threatening marine life and coastal ecosystems.",
  "A magnitude 7.2 earthquake struck the coast of Chile, triggering a tsunami warning. Coastal communities were evacuated as emergency crews worked to assess the damage. The quake caused widespread power outages and significant damage to infrastructure, including roads and buildings.",
  "The United Nations issued a stark warning about the accelerating pace of climate change, emphasizing the need for immediate and drastic action to reduce greenhouse gas emissions. The report highlighted the increasing frequency and intensity of extreme weather events, such as heatwaves, floods, and droughts.",
  "A new study published in the journal Nature found a strong link between air pollution and cognitive decline in older adults. Researchers analyzed data from thousands of participants and found that exposure to high levels of air pollution was associated with accelerated cognitive aging and an increased risk of dementia.",
  "A major cyberattack crippled several critical infrastructure systems in a European country, disrupting transportation, energy, and financial services. Authorities are investigating the source of the attack and working to restore essential services. The attack has raised concerns about the vulnerability of critical infrastructure to cyber threats.",
  "The International Space Station successfully conducted a spacewalk to repair a vital piece of equipment, averting a potential crisis for the orbiting laboratory. The spacewalk was conducted by two astronauts who successfully replaced a faulty component, ensuring the continued operation of the space station.",
  "A groundbreaking new cancer treatment has shown promising results in early clinical trials, offering hope for patients with previously untreatable forms of the disease. The new therapy targets specific genetic mutations in cancer cells, allowing for more personalized and effective treatments.",
  "A severe drought is impacting agricultural production across several regions, leading to concerns about food shortages and rising prices. Farmers are struggling to cope with the lack of rainfall, which has significantly reduced crop yields and livestock production.",
  "A major political scandal erupted after leaked documents revealed evidence of corruption within the highest levels of government. The revelations have sparked widespread protests and calls for the resignation of several high-ranking officials.",
  "A historic agreement was reached between two long-time adversaries, ending decades of conflict and paving the way for peace and reconciliation. The agreement includes provisions for disarmament, the return of refugees, and the establishment of a joint economic development fund.",
  "A wildfire raging in the western United States has forced thousands of residents to evacuate their homes, as firefighters struggle to contain the blaze. The wildfire has already consumed hundreds of acres of forest and is threatening several communities.",
  "A new report from the World Health Organization warns of a global resurgence of infectious diseases, urging increased investment in public health infrastructure. The report highlights the growing threat of antibiotic resistance and the need for improved surveillance and response systems.",
  "A landmark Supreme Court ruling overturned a controversial law, sparking widespread protests and calls for further legal action. The ruling has significant implications for civil rights, social justice, and the balance of power between the federal government and the states.",
  "A major oil spill off the coast of California has caused significant environmental damage, threatening marine life and coastal ecosystems. Thousands of gallons of oil have leaked into the ocean, impacting wildlife, fisheries, and tourism.",
  "A powerful hurricane is expected to make landfall in the coming days, prompting mandatory evacuations and emergency preparations. Coastal communities are bracing for the impact of the storm, which is expected to bring strong winds, heavy rain, and a potential storm surge.",
  "A groundbreaking new technology has the potential to revolutionize renewable energy production, offering a cleaner and more sustainable future. The new technology, which harnesses the power of solar energy more efficiently, could significantly reduce reliance on fossil fuels.",
  "A major earthquake struck a densely populated region, causing widespread destruction and leaving thousands homeless. Rescue and relief efforts are underway, with emergency crews working to search for survivors and provide aid to those affected.",
  "A new study found that a common household chemical may be linked to an increased risk of certain types of cancer, prompting calls for stricter regulations. The study has raised concerns about the potential health risks associated with widespread use of the chemical.",
  "A historic summit between world leaders concluded with a commitment to address global challenges such as climate change, poverty, and inequality. The leaders agreed to increase funding for international development, strengthen global cooperation, and promote sustainable development.",
  "A major tech company announced a new product that is expected to revolutionize the way people interact with technology. The new product, a virtual reality headset with advanced haptic feedback, promises to offer immersive and interactive experiences.",
  "A severe winter storm has paralyzed transportation across much of the country, leaving millions stranded and facing power outages. The storm has brought heavy snow, strong winds, and freezing temperatures, disrupting travel and causing widespread disruption.",
  "A team of scientists has made a groundbreaking discovery, identifying a new species of dinosaur in a remote region of South America. The discovery provides new insights into the evolution and diversity of dinosaurs during the Cretaceous period.",
  "A major art heist has left authorities baffled, with priceless works of art stolen from a world-renowned museum. The theft has sparked a global manhunt for the perpetrators and raised concerns about the security of art collections worldwide.",
  "A new report warns of a looming global food crisis, driven by climate change, conflict, and economic instability. The report highlights the increasing vulnerability of food systems to shocks, and calls for urgent action to ensure food security for all.",
  "A major social media platform has been accused of spreading misinformation and inciting violence, facing calls for increased regulation. The platform has come under fire for its role in amplifying extremist content and fueling social unrest.",
  "A groundbreaking new medical procedure has successfully restored sight to a patient who had been blind for years. The procedure, which involves transplanting stem cells into the retina, offers hope for millions of people suffering from vision loss.",
  "A major volcanic eruption has forced the evacuation of thousands of residents, as lava flows threaten to engulf nearby villages. The eruption has also caused widespread ashfall, disrupting air travel and affecting air quality.",
  "A new study found that a widely used medication may have serious side effects, prompting a recall and raising concerns about patient safety. The study found a link between the medication and an increased risk of heart attack and stroke.",
  "A historic election has resulted in a major shift in the political landscape, with a new leader promising to usher in an era of change. The election has been hailed as a turning point in the country's history, with many hoping for a brighter future.",
  "A major flood has inundated entire communities, leaving thousands of people displaced and in need of emergency assistance. Rescue and relief efforts are underway, with emergency crews working to evacuate residents and provide food, water, and shelter.",
  "A team of scientists has successfully landed a spacecraft on a distant asteroid, marking a significant milestone in space exploration. The mission provides valuable data about the composition and structure of asteroids, which could help to protect Earth from future impacts.",
  "A major wildfire has ravaged a popular tourist destination, destroying homes and businesses and forcing the evacuation of thousands of visitors. The wildfire has also caused significant air quality problems, impacting the health of residents and tourists.",
  "A new report warns of a global water crisis, as rising demand and declining supplies threaten to exacerbate conflicts and displacement. The report highlights the urgent need for investments in water infrastructure and more sustainable water management practices.",
  "A major earthquake has struck a densely populated region, causing widespread destruction and leaving thousands homeless. Rescue and relief efforts are underway, with emergency crews working to search for survivors and provide aid to those affected.",
  "A historic agreement has been reached between world leaders to reduce greenhouse gas emissions and combat climate change. The agreement sets ambitious targets for reducing emissions and aims to limit global warming to 1.5 degrees Celsius.",
  "A major tech company has announced plans to lay off thousands of employees, citing economic uncertainty and declining revenues. The layoffs have sparked concerns about job security and the impact on the local economy.",
  "A new study has found that a common household chemical may be linked to an increased risk of certain types of cancer, prompting calls for stricter regulations. The study has raised concerns about the potential health risks associated with widespread use of the chemical.",
  "A major political scandal has erupted, with allegations of corruption and abuse of power by high-ranking officials. The allegations have sparked widespread protests and calls for the resignation of those implicated.",
  "A powerful hurricane has made landfall, causing widespread devastation and leaving millions without power. The hurricane has brought strong winds, heavy rain, and a storm surge, causing significant damage to homes, businesses, and infrastructure.",
  "A groundbreaking new medical procedure has successfully restored sight to a patient who had been blind for years. The procedure, which involves transplanting stem cells into the retina, offers hope for millions of people suffering from vision loss.",
  "A major oil spill has caused significant environmental damage, threatening marine life and coastal ecosystems. Thousands of gallons of oil have leaked into the ocean, impacting wildlife, fisheries, and tourism.",
];
